name: 'Run calculator build and tests'
on:
  push:
  workflow_dispatch:
  pull_request:

permissions:
  contents: read
  actions: write

jobs:
  build:
   runs-on: ubuntu-latest
   steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Run Makefile
        run: |-
          cd calculator
          make
  test_setup:
    runs-on: ubuntu-latest
    outputs:
      test_list: ${{ steps.get_list.outputs.TESTS_JSON }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Get list of tests
        id: get_list
        run: |-
          cd calculator
          export TESTS_JSON=$(find ./tests -type f -exec test -x {} \; -print | jq -Rsc 'gsub("\\s*$";"") | split("\n") | sort')
          echo "TESTS_JSON=$TESTS_JSON" >> $GITHUB_OUTPUT
  test:
    runs-on: ubuntu-latest
    needs: [build, test_setup]
    strategy:
      fail-fast: true
      matrix:
        test: ${{ fromJSON(needs.test_setup.outputs.test_list) }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Run Makefile
        run: |-
          cd calculator
          make
      - name: Run test
        run: |-
          cd calculator
          ${{ matrix.test }} "$(pwd)/calculator -q"
